# permissions for end users to edit redisoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redisoperator-editor-role
rules:
- apiGroups:
  - db.payu.com
  resources:
  - redisoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db.payu.com
  resources:
  - redisoperators/status
  verbs:
  - get
