# permissions for end users to view redisoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redisoperator-viewer-role
rules:
- apiGroups:
  - db.payu.com
  resources:
  - redisoperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - db.payu.com
  resources:
  - redisoperators/status
  verbs:
  - get
